In [1]:
import pandas as pd

In [2]:
import numpy as nm

In [3]:
import matplotlib.pyplot as plt

In [4]:
df=pd.read_csv('iris.csv')

In [5]:
df.head()

sepal.length  sepal.width  petal.length  petal.width variety
0           5.1          3.5           1.4          0.2  Setosa
1           4.9          3.0           1.4          0.2  Setosa
2           4.7          3.2           1.3          0.2  Setosa
3           4.6          3.1           1.5          0.2  Setosa
4           5.0          3.6           1.4          0.2  Setosa

In [6]:
df.isnull().sum()

sepal.length    0
sepal.width     0
petal.length    0
petal.width     0
variety         0
dtype: int64

In [7]:
from sklearn.model_selection import train_test_split

In [8]:
X=df[['sepal.length','sepal.width','petal.length','petal.width']]

In [9]:
y=df['variety']

In [10]:
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25)

In [11]:
print(X_train.shape)

(112, 4)


In [12]:
print(X_test.shape)

(38, 4)


In [13]:
print(y_train.shape)

(112,)


In [14]:
print(y_test.shape)

(38,)


In [15]:
from sklearn.preprocessing import StandardScaler

In [16]:
sc=StandardScaler()

In [17]:
X_train=sc.fit_transform(X_train)

In [18]:
X_test=sc.transform(X_test)

In [20]:
from sklearn.naive_bayes import GaussianNB

In [21]:
NB=GaussianNB()

In [22]:
NB.fit(X_train,y_train)

GaussianNB()

In [23]:
y_pred=NB.predict(X_test)

In [24]:
print(y_pred)

['Virginica' 'Virginica' 'Versicolor' 'Setosa' 'Versicolor' 'Setosa'
 'Virginica' 'Virginica' 'Setosa' 'Virginica' 'Versicolor' 'Virginica'
 'Setosa' 'Setosa' 'Versicolor' 'Virginica' 'Virginica' 'Setosa'
 'Virginica' 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Versicolor'
 'Virginica' 'Virginica' 'Setosa' 'Virginica' 'Virginica' 'Versicolor'
 'Virginica' 'Setosa' 'Setosa' 'Versicolor' 'Versicolor' 'Virginica'
 'Virginica' 'Versicolor']


In [30]:
from sklearn.metrics import confusion_matrix,precision_score,accuracy_score,recall_score,classification_report 

In [26]:
cm=confusion_matrix(y_test,y_pred)

In [27]:
print(cm)

[[11  0  0]
 [ 0 11  1]
 [ 0  0 15]]


In [31]:
cr=classification_report(y_test,y_pred)

In [32]:
print(cr)

              precision    recall  f1-score   support

      Setosa       1.00      1.00      1.00        11
  Versicolor       1.00      0.92      0.96        12
   Virginica       0.94      1.00      0.97        15

    accuracy                           0.97        38
   macro avg       0.98      0.97      0.97        38
weighted avg       0.98      0.97      0.97        38



In [35]:
pr =precision_score(y_test,y_pred,average='micro')

In [36]:
print(pr)

0.9736842105263158


In [40]:
ac=accuracy_score(y_test,y_pred)

In [41]:
print(ac)

0.9736842105263158


In [42]:
rs=recall_score(y_test,y_pred,average='micro')

In [43]:
print(rs)

0.9736842105263158


In [44]:
error_rate=1-ac

In [45]:
print(error_rate)

0.02631578947368418
